
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Stockholm"
      time: "14:00"
      interval: "daily"
      day: "tuesday"
    target-branch: "develop"
